export const images = {
    "Aphids": require("../assets/images/Aphids.jpg"),
    "Apple Black rot": require("../assets/images/Apple Black rot.jpg"),
    "Apple scab": require("../assets/images/Apple scab.jpg"),
    "Apple Cedar apple rust": require("../assets/images/Apple Cedar apple rust.jpg"),
    "Apple healthy": require("../assets/images/Apple healthy.jpg"),
    "Blueberry healthy": require("../assets/images/Blueberry healthy.jpg"),
    "Cherry (including sour)Powdery mildew": require("../assets/images/Cherry (including sour)Powdery mildew.jpg"),
    "Cherry (including sour) healthy": require("../assets/images/Cherry (including sour) healthy.jpg"),
    "Corn (maize)Cercospora leaf spot Gray leaf spot": require("../assets/images/Corn (maize)Cercospora leaf spot Gray leaf spot.jpg"),
    "Corn (maize)Common rust": require("../assets/images/Corn (maize)Common rust.jpg"),
    "Corn (maize)Northern Leaf Blight": require("../assets/images/Corn (maize)Northern Leaf Blight.jpg"),
    "Corn (maize) healthy": require("../assets/images/Corn (maize) healthy.jpg"),
    "Grape Black rot": require("../assets/images/Grape Black rot.jpg"),
    "Grape Esca (Black Measles)": require("../assets/images/Grape Esca (Black Measles).jpg"),
    "Grape Leaf blight (Isariopsis Leaf Spot)": require("../assets/images/Grape Leaf blight (Isariopsis Leaf Spot).jpg"),
    "Grape healthy": require("../assets/images/Grape healthy.jpg"),
    "Orange Haunglongbing (Citrus greening)": require("../assets/images/Orange Haunglongbing (Citrus greening).jpg"),
    "Peach Bacterial spot": require("../assets/images/Peach Bacterial spot.jpg"),
    "Peach healthy": require("../assets/images/Peach healthy.jpg"),
    "Pepper, Bacterial spot": require("../assets/images/Pepper, Bacterial spot.jpg"),
    "Pepper, healthy": require("../assets/images/Pepper, healthy.jpg"),
    "Potato Early blight": require("../assets/images/Potato Early blight.jpg"),
    "Potato Late blight": require("../assets/images/Potato Late blight.jpg"),
    "Potato healthy": require("../assets/images/Potato healthy.jpg"),
    "Raspberry healthy": require("../assets/images/Raspberry healthy.jpg"),
    "Soybean healthy": require("../assets/images/Soybean healthy.jpg"),
    "Squash Powdery mildew": require("../assets/images/Squash Powdery mildew.jpg"),
    "Strawberry Leaf scorch": require("../assets/images/Strawberry Leaf scorch.jpg"),
    "Strawberry healthy": require("../assets/images/Strawberry healthy.jpg"),
    "Tomato Bacterial spot": require("../assets/images/Tomato Bacterial spot.jpg"),
    "Tomato Early blight": require("../assets/images/Tomato Early blight.jpg"),
    "Tomato Late blight": require("../assets/images/Tomato Late blight.jpg"),
    "Tomato Leaf Mold": require("../assets/images/Tomato Leaf Mold.jpg"),
    "Tomato Septoria leaf spot": require("../assets/images/Tomato Septoria leaf spot.jpg"), 
    "Tomato Spider mites Two-spotted spider mite": require("../assets/images/Tomato Spider mites Two-spotted spider mite.jpg"),
    "Tomato Target Spot": require("../assets/images/Tomato Target Spot.jpg"),
    "Tomato Yellow Leaf Curl Virus": require("../assets/images/Tomato Yellow Leaf Curl Virus.jpg"),
    "Tomato mosaic virus": require("../assets/images/Tomato mosaic virus.jpg"),
    "Tomato healthy": require("../assets/images/Tomato healthy.jpg"),
}